version: '3.1'
services:


  web:
    container_name: whelp_task
    build: .
    restart: always
    depends_on:
      - db
      - rabbit
    env_file: .env
  

  celery:
    container_name: whelp_celery
    build: .
    restart: always
    command: celery -A celery_tasks.app.celery_app worker --loglevel=INFO
    depends_on:
      - web
      - db
      - rabbit
    env_file: .env


  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    env_file: .env

  rabbit:
    image: rabbitmq:3
    restart: always
    env_file: .env

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "web"