# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=whelptask
      - MYSQL_USER=whelp_user
      - MYSQL_PASSWORD=userpass
      - MYSQL_ROOT_PASSWORD=rootpass

  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080